# Generated by Django 5.2.7 on 2026-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
